# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "53eb8bac00dcac185e719de2e1721e66"
name = "Brad NextGen Wishlist"
handle = "brad-nextgen-wishlist-1"
application_url = "https://vhs-separation-tampa-blocked.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "bradnextgenwishlist.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,write_products"

[auth]
redirect_urls = [
  "https://vhs-separation-tampa-blocked.trycloudflare.com/auth/callback",
  "https://vhs-separation-tampa-blocked.trycloudflare.com/auth/shopify/callback",
  "https://vhs-separation-tampa-blocked.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[app_proxy]
url = "https://vhs-separation-tampa-blocked.trycloudflare.com/api"
subpath = "prapp"
prefix = "apps"

[pos]
embedded = true
